### ISSUE TITLE
Fix and re-enable failing Matlab tests

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#111]
Several Matlab tests were failing on the build servers (some also locally), to get the servers up and running these were disabled in #110. These need to be fixed/re-written and re-enabled. Below is a `.txt` file containing details about the various tests that were failing.

The commits disabling these tests were: bea56145a279b33188768a4f400fc4949dfa8b82 85eaec5b1801b20f822ea3304f84d77bc75a0b48

The disabled tests are:
- [x] `test_gen_sqw_cylinder::test_gen_sqw_cyl` -  single assertion disabled https://github.com/pace-neutrons/Horace/issues/155
- [x] `test_gen_sqw_powder::test_powder_cuts` - test function disabled https://github.com/pace-neutrons/Horace/issues/155
- [ ] `test_multifit::test_fit_single_or_array2` - test function disabled
- [x] `test_tobyfit::test_tobyfit_refine_crystal_1` - test script disabled https://github.com/pace-neutrons/Horace/issues/188
- [x] `test_tobyfit::test_tobyfit_1` - test script disabled
- [x] `test_tobyfit::test_tobyfit_let_2` https://github.com/pace-neutrons/Horace/issues/172
- [x] `test_tobyfit` - https://github.com/pace-neutrons/Horace/issues/172
- [x] `test_sqw` - suite disabled https://github.com/pace-neutrons/Horace/issues/139
- [x] `test_mslice_utilities` - suite disabled #182

[matlab_failing_tests.txt](https://github.com/pace-neutrons/Horace/files/4127719/matlab_failing_tests.txt)

**Outputs:**
- Tests enabled and passing on builds servers and locally

Depends on: https://github.com/pace-neutrons/Horace/issues/126

**Comment by abuts** [comment]
strange list. 
I have just run the tests on iDaaaS machine and see only test_multifit::test_fit_single_or_array2 failing.
is it possible that these test are running long time? The run on iDaaaS machine takes 48min.

**Comment by hsautessella** [comment]
Only the `test_sqw` tests were timing out - and that was due to an error with the MPI workers. I've put the error messages for the failing tests in the `matlab_failing_test.txt` file

**Comment by hsautessella** [comment]
`test_gen_sqw_cylinder::test_gen_sqw_cyl` and `test_gen_sqw_powder::test_powder_cuts` only seem to fail for me if using mex. If I run `runtests('test_gen_sqw_for_powder')` (from within the `_test` folder) and `herbert_config.use_mex_C = true` then the tests both fail. If I run the same thing with `herbert_config.use_mex_C = false` the tests pass.

If I run `test_gen_sqw_for_powders` through CTest or `validate_horace` then the tests pass.

**Comment by hsautessella** [comment]
I can't actually find `test_multifit::test_fit_single_or_array2` anywhere. Has it been removed? I think this ticket is closable now
