### ISSUE TITLE
Fix and re-enable failing Herbert tests

### ISSUE THREAD

**Issue by hsautessella** [pace-neutrons/Horace#112]
- [x] https://github.com/pace-neutrons/Herbert/issues/39 - mslice_objects (Linux only)
- [x] https://github.com/pace-neutrons/Herbert/issues/46 - test_mpi
- [x] https://github.com/pace-neutrons/Herbert/issues/70 - test_utilitites
- [x] https://github.com/pace-neutrons/Herbert/issues/92 + pace-neutrons/Herbert#126 - test_job_dispatcher
- [x] https://github.com/pace-neutrons/Herbert/issues/123  - fixing different tests overwriting the same configuration on Jenkins
 - [x] https://github.com/pace-neutrons/Herbert/issues/121 different configuration for Linux and Windwos Jenkins

**Comment by hsautessella** [comment]
Blocked waiting on #129
