### ISSUE TITLE
TRACK: CI issues

### ISSUE THREAD

**Issue by cmarooney-stfc** [pace-neutrons/Horace#1263]
Issues on CI

CHRIS 28.10.23 marking low priority issues as done

 - [x] Jacob #1220 [DISCUSSION] ZERO PRIORITY
 - [x] Jacob #1054 [MVP]
 - [x] Jacob #676 [EPIC] LOW PRIORITY MAYBE AARON
 - [x] Jacob #598 [TESTING] LOW PRIORITY MAYBE AARON
 - [x] Jacob #559 [FUTURE]
 - [x] Ghost #353 [FUTURE]
 - [x] Nick #271 [POST-CONSTRUCTION]
 - [x] Nick #266 [DISCUSSION] FILENAMES JENKINS NOT A PROBLEM
 - [x] Nick #47 [POST-CONSTRUCTION]
 - [x] Nick #46 [POST-CONSTRUCTION]
 - [x] Nick #45 [POST-CONSTRUCTION]
 - [x] Nick #30 [EPIC, FEATURE, POST-CONSTRUCTION]

**Comment by cmarooney-stfc** [comment]
Closed as all low priority or fixed. Possible Aaron tasks tracked in #1361

**Comment by cmarooney-stfc** [comment]
Closed as all low priority or fixed. Possible Aaron tasks tracked in https://github.com/pace-neutrons/Horace/issues/1361
