### ISSUE TITLE
TRACK: Tobyfit issues

### ISSUE THREAD

**Issue by cmarooney-stfc** [pace-neutrons/Horace#1267]
Issues on Tobyfit

CHRIS 28.10.23 low priority issues marked as fixed

 - [x] Alex #917 [DISCUSSION, POST-CONSTRUCTION]
 - [x] Olivier #856 [BUG] LOW PRIORITY
 - [x] Alex #840  LOW PRIORITY
 - [x] Becky #732 [POST-CONSTRUCTION]

**Comment by cmarooney-stfc** [comment]
marked fixed as all issues closed with low priority
