### ISSUE TITLE
Post MVP epic to track miscellaneous (unclassified) issues

### ISSUE THREAD

**Issue by cmarooney-stfc** [pace-neutrons/Horace#1270]
issues without obvious classification

 - [ ] Alex #983 
 - [ ] Alex #826 
 - [ ] Nick #578 [ONGOING]
 - [ ] Nick #576 [ONGOING]
 - [ ] Chris #451 [MVP, HERBERT]
 - [ ] Alex #402 [MVP]
 - [ ] Ghost #321 [BLOCKED, POST-CONSTRUCTION]
 - [ ] Duc #243 
 - [ ] Nick #215 [FUTURE]
 - [ ] Nick #214 [ONGOING]
 - [ ] Nick #213 [ONGOING]
 - [ ] Nick #33 [DISCUSSION, MVP]
 - [ ] Nick #21 [FEATURE, EPIC, MVP]
