### ISSUE TITLE
EPIC: modify all pixel operation which not change image shape to use apply method (THE filebacked epic)

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#1302]
There are numerous Horace operations performed over `sqw` objects, which do not change image shape but loop through all pixels and calculate DnD image as function of changes to the pixels. All these operations are currently use very similar but different pieces of code, which is, in many cases, incorrect. 

The purpose of this EPIC is to collect all these operations, reimplement them to use single piece of code, namely `apply_op` method(s) of `sqw` and `PixelData` objects, and `PageOp` object which is specific for every operation, but acts on signle block of   pixel data located in memory. 

The epic contains number of steps:

 - [x] Paging operations prototype (mask rewritten)  #1178
 - [x] PageOp improvement (sqw_eval implemented) #1304
 - [x] funceval implementation #1313
 - [x] unary operations #1324
 - [x] fiddling with sqw object interface #1343
 - [x] apply using pageOp #1346
 - [x] cat/split/combine_sqw  #1330
 - [x] join/write_nsqw_to_sqw #1402 
 - [x] IX_datset old serializable #1356
 - [x] Fix/validate binary operations (binary_op_manager_single) #1303 
 - [x] control sorting in pix-pix operations #1371
 - [x] noisify #1325 
 - [x] section #1326
 - [x] Coordinate calculations #1305
 - [x] replicate with pages #1347 done
 - [x] sigvar_set #1344
 - [x] #1323 -- small improvements for fcloser
 - [x] filebacked alignment issue #1091
 - [x] Optimize the Unary and Binary operations #29 
 - [x]  `get_new_handle` removal #1403 
 - [x] file-saver which allows finalizing filebacked objects #1320

**Comment by abuts** [comment]
Closed as completed, remain work is related to optimization/code dept moved to #1455
