### ISSUE TITLE
TRACK: Update on new issues 15.11.23

### ISSUE THREAD

**Issue by cmarooney-stfc** [pace-neutrons/Horace#1386]
(a) 
Update tracking new issues since previous sprint review 2.11.23

(b)
Review previous prioritisation

------

(a) New issues since 2.11.23

Object lookup/detectors
 - [ ] Toby #1383 subticket of #1340 see below - 1383 in progress other tickets to come - PR for 1383 in and reviewed. 1383 to finish in 7 w/d, including other tickets to will generate script, work half done. Also related to Jacob's dqmat on the fly work. 

Fitting/filebacked/optimization
 - [ ] Alex #1372 (both of these not in epic) - deferred as optimisation tasks - coupled to Jacob dqmat work? not scheduled (both)
 - [ ] Alex #1364 

Bugs
 - [ ] Alex #1371 part of epic #1302 (below)

Documentation
 - [ ] Jacob #1367  for apply and pageOp - scope may need clarifying given prioritization of pageOp

(b) Previously prioritised (high priority only, not including PACE-Python)

Alex (EPIC) #1302 in progress (main filebacked epic) - to finish in coming sprint
 - [ ] Alex #1352 part of #1302
 - [ ] Alex #1347 part of #1302
 - [ ] Alex #1342 part of #1302
 - [ ] Alex #1330 part of #1302 current task
 - [ ] Alex #1320 part of #1302
 - [ ] New ticket to be added - remove old interface

Next step - validate Horace using training course - likely to generate tickets - #1314

Pre-release of 4.0.0 made Monday as Chinese users could not use IDAaaS and needed release (see Horace releases page)

Other
 - [ ] Alex #1341 Jacob to do as part of docs - issues arising may include 
 - [ ] Alex #1314 (may delay #1348, transferred to Jacob for minimal update) *next step*
 - [ ] Alex #1350 Chris has PR in progress
 - [ ] Alex #1345 estimate 1d, after filebacked
 - [ ] Alex #1354 performance issue; to be prioritized
 - [ ] Chris #1299 docs
 - [ ] Chris #1298 in progress, subject to Toby work above
 - [ ] Chris #1340 detector dependency on run - with Toby 
 - [ ] Chris #1338 awaits Duc population of nxspe
 - [ ] Chris #1230 discussion (high priority low urgency fold in with algorithm docs)
 - [ ] Chris #1025 still to do
 - [ ] For Toby #935 maybe fixed by #801 Toby to check

Refer back to #1361 last tracking report for others not covered here

**Comment by abuts** [comment]
clolsed as superseeded by next reviews
