### ISSUE TITLE
TRACK: Sprint review 12.12.23

### ISSUE THREAD

**Issue by cmarooney-stfc** [pace-neutrons/Horace#1434]
(a) Prioritization of new issues since last sprint review 15.11.23

Process

 - [ ] #1404

Filebacked

 - [ ] #1403 
 - [ ] #1402 

Tobyfit/Detectors

 - [ ] #1398 

Parallel

 - [ ] #1393 [POST-CONSTRUCTION, SCARF check of fixes to IDAaaS #1292, #1391]

Tests

 - [ ] #1387 [BUG, TESTS, TECHNICAL DEBT]

Filebacked epic #1302 
 - remaining time estimated as 3 weeks = 19.12.23

----------------------

RADU/Jacob 9am 29.11

---------

(b) Previous issues still outstanding

Testing

 - [ ] Alex #1314
 - [ ] Alex #1345 
 Jacob  created #1409 docs issue on mask points behaviour
 mask other issue is low priority - check number on Toby tickets 

Fitting/filebacked/optimization
Both low priority to be done after validation

 - [ ] Alex #1372 (both of these not in epic) - deferred as optimisation tasks - coupled to Jacob dqmat work? not scheduled (both)
 - [ ] Alex #1364 

Filebacked
remaining filebacked tickets within 3 week estimate

 - [ ] Alex #1352 part of #1302
 - [ ] Alex #1347 part of #1302
 - [ ] Alex #1330 part of #1302 current task
 - [ ] Alex #1320 part of #1302
 - [ ] #1345 low priority
 - [ ] New ticket to be added - remove old interface #1403 ticket now added - part of filebacked 3 weeks

Documentation

 - [ ] Jacob #1367  for apply and pageOp - scope may need clarifying given prioritization of pageOp
awaiting completion of filebacked
 - [ ] #1341 Jacob to do as part of docs - 
 - [ ] Chris #1299 docs

Detectors/Tobyfit
 - [ ]  #1350 
 - [ ] Chris #1298 in progress, subject to Toby work above
 - [ ] Chris #1338 awaits Duc population of nxspe
 Toby to progress this

Other
 - [ ] Alex #1354 performance issue; to be prioritized
 - [ ] Alex #1345 estimate 1d, after filebacked
 - [ ] Chris #1025
 - [ ] For Toby #935 maybe fixed by #801 Toby to check

**Comment by cmarooney-stfc** [comment]
closed as superseded by #1470
