### ISSUE TITLE
EPIC: Horace 4 user experience

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#1464]
This epic summarizes issues identified during Horace analysis using Horace training course. The analyis is finished and these the issues to fix.

 - [x] uoffset and offset #1466
 - [x] modifications to user guide #1472
 - [x] xycursor broken? #1474
 - [x] `change_crystal_horace` old description #1491
 - [x] legacy alignment for legacy files #1492 
 - [x] old `head` form error #1493
 - [x] `'-set_pix'` in replicate(dnd) #1495
 - [x] cut with default ranges #1499
 - [x] update_file_format verbocity #1498
 - [x] old multifit conversion #1505
 - [x] are image captions valid? #1511
 - [x] incorrect return from plot #1501
 - [x] sphere proj issues #1533
 - [x] missing function? #1542
 - [x] better spherical coordinate system description #1549
 - [x] legacy alignment for cuts #1554
