### ISSUE TITLE
TRACK: Sprint review 20.2.2024

### ISSUE THREAD

**Issue by cmarooney-stfc** [pace-neutrons/Horace#1555]
Major areas - need to ensure closed or track
 - spherical projection - done for preconstruction. Documentation ticket #1508. Bug tickets #1183. Probable original ticket #943. Other tickets may refer to individual projection changes. Epic for generic projections is #34.
 - cylindrical projection - ready to start modulo possibility of postconstruction improvements to spherical
                                      - can roll mod-q axis (current measure inv.A) change scale to hkl,  for spherical, into this task
 - focussed projection (tickets only) - ticketing done
 - detector info - received from Duc modulo spectra to workspace maps missing (mantid crash/glitch)
 - profiling - estimate 2 weeks
 - Fan IDAAAS performance issue - fix issued, Fan ticket closed. Find current max file size, discuss with Excitations. Import test scripts into our github

New issues:

Alex -
 - [ ] #1554 in hand, needs fixing
 - [ ] #1553 not critical but extends to half Matlab platforms - parallel toolbox not affected, problem Windows only. Prioritise finding out extent of problem (still post-construction) - Jacob to scope this sprint
 - [ ] #1538 can be postponed
 - [ ] #1534 - post-construction, discuss with Duc, continue manual updating of docs

Jacob - 
 - [ ] #1532 - timeboxed, did not fix, leave for post-construction
 - [ ] #1553 with AB, Jacob to scope

Toby -
 - [ ] #1536 comment added on use of w rather than wt

Chris - 
 - [ ] #1544 in progress

Still open from last time:

Alex - 
 - [ ] #1511 docs only - before end construction, after cylindrical projection
 - [ ] #1505 JW to take on PR open
 - [ ] #1497 some may be fixed, not with spherical, prioritise
 - [ ] #1481 performance issue, leave to post-construction
 - [ ] (sprint end 9.1) #1465 low priority post construction
 - [ ] (sprint end 9.1) #1436 post construction

Jacob - 
 - [ ] #1524 - Alex to pick up, low priority pre-construction
 - [ ] #1519 - prioritise, from Christian. Also press Duc for SpinW interface function, DUc passed fix to Christian JW to close
 - [ ] #1513
 - [ ] #1490
 - [ ] #1489 future
 - [ ] #1488 part of profiling, Toby to generate
 - [ ] (sprint end 9.1) #1448 post-construction medium-high priority
 - [ ] (sprint end 9.1) #1441 post-construction

Toby - 
 - [ ] #1485 post-construction
 - [ ]  (sprint end 9.1) #1459 post-construction

**Comment by cmarooney-stfc** [comment]
closed as superseded by #1594
