### ISSUE TITLE
TRACK: Sprint review 05.03.24

### ISSUE THREAD

**Issue by cmarooney-stfc** [pace-neutrons/Horace#1594]
Major areas - need to ensure closed or track

 WHAT MUST WE FINISH BY MAR 31?
 - cylindrical projection - ready to start modulo possibility of postconstruction improvements to spherical
                                      - can roll mod-q axis (current measure inv.A) change scale to hkl,  for spherical, into this task
                                      - issues added #1578 TO BE DONE, estimate 3d
 - energy focussed projection (tickets only) - ticketing being done by Alex - POST CONSTRUCTION #1596
 - detector info - received from Duc modulo spectra to workspace maps missing (mantid crash/glitch) - TO BE DONE Duc still to do, half day work
 - profiling - - TO BE DONE - data from Duc received, comparison in progress. SQW load reduced but may be format conversion - initial timings w/e 9/3, awaiting data from Toby
 - Fan IDAAAS performance issue - fix issued, Fan ticket closed. Find current max file size, discuss with Excitations. Import test scripts into our github. Check usability of Alex instructions. Issue is cache usage of memory for file transfer - there are different takes on this. Chris to consider how instructions work for reader
 - Fan IDAAAS issue .- pending state causing crash. Fixed but not reproducible - machine info with Fan
 - SLURM cluster unavailable after SL7 purge - JW to contact Fan to reinstate. Noting gen_sqw did not work well with SLURM. Also bulleted document describing stages of usability

New:

Alex -

 - [ ] #1591 legacy alignment - issue with matrix separation (U/rotation, B/scale to crystal cartesian) - realignment of H3 file may cause problems - BUG, SO TO BE DONE first,  in progress, (check Ross use of 3.6.3) then Cylindrical - 20/3 finish
 - [ ] #1583 reassign to JW one hour's work
 - [ ] #1572 POST-CONSTRUCTION
 - [ ] #1561 ditto
 - [ ] #1560 ditto

Jacob -

 - [ ] #1585  POST-CONSTRUCTION
 - [ ] #1566  PR open

Previous issues:

Alex -
 - [ ] #1553 not critical but extends to half Matlab platforms - parallel toolbox not affected, problem Windows only. Prioritise finding out extent of problem (still post-construction) - Jacob to scope this sprint NOT YET SCOPED, TO BE DONE this sprint
moved to JW below
 - [ ] #1538 can be postponed pOST CONSTRUCTION

Jacob - 
 - [ ] #1532 - timeboxed, did not fix, leave for post-construction, disabled not fixed
 - [ ] #1553 with AB, Jacob to scope moved from above TO BE DONE

Toby -
 - [ ] #1536 comment added on use of w rather than wt POST CONSTRUCTION

Chris - 
 - [ ] #1544 in progress

See #1555 for even earlier issues still open - there are quite a few

**Comment by cmarooney-stfc** [comment]
closed as superseded by #1610
