### ISSUE TITLE
PRIORITIZATION: Post-construction 1a

### ISSUE THREAD

**Issue by cmarooney-stfc** [pace-neutrons/Horace#1653]
Tasks to do and time estimates

1. PACE-integration CI not working - JW to talk to Adam, also Duc re Spinw disconnect - fill in ticket CHECK TICKET
2. Documentation - JW
3. Read H4 output from H3 - who? - CHECK TICKET

- deprecate Horace 3 (after closeout) and items leading to this (=Ross flipchart)
check reading H4 from H3
- API (=Radu); document changes where interface can't be provided - another meeting/s with Radu
move ross email to Horace-3 deprecation doc (Pace newsletter) 
- parallelization (gen_sqw, cut/symmetrise, Tobyfit) - 
- cut not benchmarked, symmetrise does not use parallel, *fit working, gen working, unary/binary not working, virtual clusters gone: continue delaying some benchmarking, prioritise making parallelised subject to being overall feature complete
- filebacked - ok except for tobyfit (special case, not before closeout, multifit ok) -  shift pixels awaits assessment of energy focus cut
- generic projections - except for instrument projection in tobyfit, but that is closeout (relates to event mode)
- python interface - done - mo using to learn
- generic minimiser - have interface for other minimisers, could do other grad project moving on from Joshua - TGP, JW to explore
- new SQW (includes instruments, detectors to be done, see below) -ok
- modelling codes (Euphonic, SpinW, Brille) - Christian says SpinW working, David (was) working with Euphonic FRANZ!
also release versions of Euphonic, SpinW - JW to discuss with Duc - report at next sprint
- all tested/testing? - more code coverage needed

Things needing reprioritisation:

 1. Profiling - speed was not identified as a problem in Ross identification of issues. Should we keep this deprioritised? #1490, #1488 data from Toby
 4. SLURM cluster availability after move away from SL7.

New issues:
 - [ ] #1646 (Alex)
 - [ ] #1643 (Jacob)
 - [ ] #1639 (Alex)
 - [ ] #1637 (Jacob)
 - [ ] #1630 (Alex)
 - [ ] #1629 (Alex)
 - [ ] #1616 (Alex)
 - [ ] #1613 (unassigned, Alex says may be ill-posed)

Issues in progress:

 - [ ] #1591 legacy alignment (Alex)
 - [ ] #1553 (Jacob)
 - [ ] #1544 hashing separated into excess number of ops (done), hashing algorithm (in progress), save/load hashes (to do) #1636 (Chris)

User bugs:
 - [ ] #1649 (Alex, Jacob)

Issues postponed till after closeout:
 - parallel fitting not compatible with SpinW (Duc, ...) - ticket?
 - detector data import (Duc, Toby-->Chris) - ticket? - related detpar tickets are #1432 #1350 #1298 #1338 #1398
 - normalised polygons (jacob) - ticket?
 - help for power users e.g. Radu
 - [ ] #1596 
 
Issues to be completed before closeout:
 - NB closeout timetabled for 31 August
 - backward compatibility (3-->4) and conversion between them #1632 (Jacob)
 - reduction in duplicate messages from parallel workers
 - #1612 noting that Jacob says cut-sym will work for this (Jacob)
 - parallel HPC settings, random initial configuration (Jacob) - may be done - #1608 #1607 #1606
 - [ ] #1611 length of time to take cuts (read/write speed on IDAAAS) - addressible in the long term, 4 solutions (not assigned)
 - [ ] #1572 (Alex)
 - [ ] #1561 (Alex)
 - [ ] #1560 (Alex)
 - [ ] #1585 (Jacob)
 - [ ] #1538 (Alex)
 - [ ] #1536 (Toby)
 - [ ] #1511 (Alex)
 - [ ] #1481 (Alex, performance issue)
 - [ ] #1465 (Alex)
 - [ ] #1436 (Alex)
 - [ ] #1519 (Jacob - looks as if this should be closed as workaround has been provided?)
 - [ ] #1513 and check other docs (Jacob)
 - [ ] #1489 (Jacob)
 - [ ] #1448 (Jacob)
 - [ ] #1441 (Jacob)
 - [ ] #1485 (Toby)
 - [ ] #1498 (Alex)
 - [ ] #1481 (Alex)
 - [ ] #1472 (Alex)
 - [ ] #1352 (Alex)
 - [ ] #1040 (Alex)
