### ISSUE TITLE
Draft TRACK: Post-construction 3 - 22/5/24 - INPROGRESS

### ISSUE THREAD

**Issue by cmarooney-stfc** [pace-neutrons/Horace#1683]
Leave:
   Jacob - Aiida hackathon end May 2 days, 1 other week
   Alex - 22-24 May AL:; July 15-Aug 2, AL; Jun 17-21, Jul 8-12, Student project re #896, #1611
   Toby - week 1 June, 2 weeks August, detail awaits closeout date
   Chris - course 22-26/7

Bugs, crashes, Excitations and other user issues
     - as previously #1660 
     - to allow for this, all durations for planned items below are doubled
     - we will revisit as time goes on to see how effective that is
     - timed items start 13/05/24

1. Alex in progress

2. Alex planned items

      a. #1671 documentation: alignment description wrong  - 6d - **end 21/05/24** - Alex adds ticket
      b. #1670 scales on non-linear projections  - 6d - **end 29/5/24** 
      c. #1639 - 4w - **end 28/6/24**
      d. #1498 - 6d - **end 6/7/24**
      e. #1616 - needs discussion but time fixed - 6d - **end 14/7/24**
      f. student project - **17-21/6/24, 8-12/7/24** - #896, #1611

3. Alex discussion items

     a. #1630 item 1; fix unknown
     b. #1611 , keep open, cannot find solution before closeout
     c. see 2e.
     d. #1040 - marked for after closeout but requiring >1 month (*calendar*) so marking for discussion now. Probably post closeout

4. Jacob in progress

     a. #1637 - PR 1648 nearly finished, moved from AB, nearly finished
     b. #1632 - PR 1642
     c. #1609 - PRs #1645 (dump to log non-debug), #1647 (warnonce)
     d. Spglib request to Fan

5. Jacob plan

      a. Standardise deprecating warning syntax - #1643 - **by 08/5/24**
      b. #1655 PACE Integration CI fix - ESTIMATE AVAILABLE by **by 08/5/24**
      c. Talk to Duc about SpinW interoperability - DISCUSSION CONCLUDED **by 08/5/24**
      d. Talk to Ross about (i) docs (ii) config needs (iii) #1606  - DISCUSSION CONCLUDED **by 08/5/24**
      e. #1608 - **by 03/7/24**
      f. #1607 - **by 17/7/24**

6. Chris/Toby (detectors)

      a. #1338 detector data input - Toby receiving data from Duc, Chris to complete insertion into Tobyfit via detectors

7. Chris (hashing)

 - [ ] #1636 (a) prescribe hashing algorithm across platforms [IN PROGRESS]; (b) save/load hashes - platform independent via reduced significant figures

9. Recent tickets

  - [ ] #1657 USER BUG - jw
  - [ ] #1656 - ab - said to be inconvient to users
  - [ ] #1654 user report - USER BUG
     
10, Items this meeting

- distinguish H3 and H4 SQWs #1672 (refs for PR and older ticket inside)
- help Radu migrate - plan strategy next week - arrange meeting (arranged for 15/5)
