### ISSUE TITLE
parallel mex writer/combiner

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#1736]
This epic is about reading/writing pixels in parallel using mex code. It overlaps with compressed Pixels IO as this mex code should support parallel pixels and possibly, do unpacking of the compressed pixels. 

The implementation would enable consistent output from pix combine procedure and allow at least twofold acceleration of long pix io operations.

 - [ ]  use `bin_io_handler` class, produced in #1700 in writing pixels by `cpp_combine` class
 - [ ] use `bin_io_handler` class produced in #1700 in reading pixels by `cpp_combine` class
 - [ ] modify `cpp_combine` class to use results of external npix blocks split procedure used by `PageOp` to divide pixel operations into page blocks.
 - [ ] modify pix write operation using mex plugin (Re #1701)
 - [ ] modify mex write plugin to use separate thread (Re #1702)
 - [ ] modify pix read operation using mex plugin
 - [ ] modify pix read plugin to use separate thread
 - [ ] prepare joint  pix IO plugin to allow parallel pix IO operations.
