### ISSUE TITLE
EPIC: issues with large number of small cuts

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/Horace#1781]
User was working with big number of small cuts and identified bunch of interconnected issues, which are the essence of this epic. They would probably separate into multiple smaller tickets

1) Incorrect experiment combine. Some parts will be sorted in #1778 but some are related to 2. here. #1778 assumes that files with the same `run_id` should contain same `IX_experiment` but in fact this should be checked and case of different `IX_experiments` dealt with. At least throw error for the beginning. 

2) slow operations if loading/doing multiple small cuts and moving objects between containers. (hashes are recalculated at loadind and if there are a lot of  small cuts loading). Claimed 7-fold deceleration. Solution -- `Hashable` class -- subclass of `serializable`. It would also allow fast comparison of hashable `IX_experiments`. Additional acceleration would be providing using `mex`-code for binning and transforming pixels into appropriate coordinate system.
- [x] hashable class:  #1788  
- [x] prerequest for #1790 : proper comparison #1147
- [x] make classes in containers hashable:  #1790 
- [ ] #896 mex-ed binning. hashable (#1790) gives 3-fold acceleration, while remaining code in Horace-3 was mexed. #896 written to enable this mexing in Horace-4

3) constant grows of `unique_references` container and its design. Design introduces additional implementation of singleton which is non-trivial to understand. Also adds all experiment's references to unique references container which for N small cuts containing M(n) references so N*M element grows for each operations with this bunch. Design and Grows -- separate but related issues. 
- [x] Prerequest for 3) -- standard form of singleton in unuque references containter Re #1791

- [x] bug in combine_experiment  #1778

**Comment by abuts** [comment]
closed as contributing tickets are all completed
