### ISSUE TITLE
EPIC: Rewrite Matlab SQW object

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#21]
Rewrite SQW object in 'new class' style and extracting data into multiple smaller classes.

 - [x] Rewrite SQW object as 'new class' style (#288)
 - [x] Implement full SQW API on new class

Refactor internal data:

 - [x] Update ISample with new attributes (#163)
 - [x] Experiment (#136)
 - [x] #191 Remove `detPar` and map onto `IX_xxx` class data
 - [x] Herbert [442](https://github.com/pace-neutrons/Herbert/issues/442) Remove duplicate instruments and samples within SQW object.
 - [x] #936 Remove duplicate instruments and samples between SQW object.
 - [x] #959 Convert detpar structs to IX_detector_arrays in compressed unique_reference_objects

 - [x] Create Map Header class and map PixBlock data #1283 
 - [x] PixelBlock (#137)
 - [x] Convert SQW/header to Experiment class, prepare for #191 adding detpar to Experiment (#702)
 - [x] #810 -- also uses dnd object within sqw

**Comment by nickbattam-tessella** [comment]
@abuts has created an initial redesign: [Horace redisign.docx](https://github.com/pace-neutrons/Horace/blob/master/documentation/design_forV4/Matlab%20Horace%20redesign.docx)

**Comment by abuts** [comment]
generic projection is now good enough not to block this epic, where only Experiment class change left

**Comment by oerc0122** [comment]
Final parts done by @cmarooney-stfc although issues remain with the interaction between new `IX_detector_array` and external functions.

C.f. #1060
