### ISSUE TITLE
PixelData file-backed operations

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#224]
The implementation of PixelData in #219 supports in-memory operation.

This ticket extends that to support file-based operation for data that is larger than machine memory with a consistent API.

The separation between in-memory and file-backed operation should be:
- transparent in PixelData public API
- transparent in higher-level Horace functions

Output:
- [x] File backed read operations #246 
- [x] File backed write operations #247
- [x] Recompute binary data #281 
- [x] Update SQW unary operations to handle large data #248
- [x] Update SQW binary operations to handle large data #249
- [ ] Update in-Horace calls to PixelData to handle large data #250
- [ ] New issue tickets created for specific functions that are non-trivial to adapt
- [x] Add page size config option #320

**Comment by hsautessella** [comment]
`Update in-Horace calls to PixelData to handle large data #250` bullet point  is superseded by https://github.com/pace-neutrons/Horace/issues/434. Since all other tasks are complete, I'm closing this in favour of #434.
