### ISSUE TITLE
blocking-messages - create C++ serializer

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#233]
Create a C++ serializer to manage blocking message content

Matlab hlp_seriaze/hlp_deserialize routines are currently used to convert message into sequence of bytes and vice versa. The routines process a structure/class tree recursively, allocating memory for every elementary array object, casting these objects into bytes and concatenating partial arrays into final continuous byte-array to transmit over serial communication channels. 

This works well for small messages but becomes extremely inefficient when pixel data have to be transmitted, as it involves multiple reallocation of large pixel arrays. 

In addition to that it makes sense to transmit pixels as single precision data like they are currently written in files, and cast into double precision at the target destination only. Current procedure does not allow to do that. 

To make serialization efficient, C++ routine should be implemented, which would calculate the size of the target structure, allocate memory once, copy appropriate parts of the transmitted structure (may be using multiple threads) into this memory performing necessary transformations (double->single) and provide the final array for further serial operations. 

Current deserializer looks efficient enough but may be improved, especially if deserialization i.e copying data from linear array to Matlab structure can be performed in parallel. 

part of #69 

Output
- [ ] fix Matlab serializer to estimate serialized object size and, possibly, implement C++ procedure for estimation of an object size.
- [ ] ability to convert data object to message body
- [ ] ability to parse message body to data object
- [ ] unit tests demonstrating reversibility
- [ ] documentation of data format

**Comment by nickbattam-tessella** [comment]
Do we need to develop a custom serializer, or can we use existing libraries to provide this functionality?

**Comment by abuts** [comment]
probably need to write our own because of the request of everything working the same way with or without mex code. CPP mpi would not work without so may be not so important in this case....

**Comment by abuts** [comment]
I think rewriting hlp serializer in C++ would be beneficial and not that difficult as there is Matlab prototype

**Comment by abuts** [comment]
and external library need to be maintained. It was undocumented access to Matlab serializar in previous Matlab versions -- unfortunately not here any more

**Comment by cmarooney-stfc** [comment]
@oerc0122 Hi Jacob - noticing that none of the boxes in the description are ticked. Could you ensure they are updated or corrected as appropriate please. Thanks
