### ISSUE TITLE
PixelData - Support large-file operation of Horace

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#250]
Update all remaining uses of the PixelData object to correctly manage the large-data use-case.

Part of #224 

**Outputs:**
All uses of PixelData rewritten to support large datasets
- [x] permute_pix_data_array (#345)
- [x] `noisify` (#352)
- [ ] `sort_pix` (#398)
- [x] `equal_to_tol` (#399)
- [ ] `combine_sqw` (#400)
- [ ] `cut` -> `cut_data_from_array` is responsible for taking cuts from an SQW object rather than a file (#401)
- [ ] `rebin_sqw`
  - I don't think this needs paging, but shallow copies of PixelData objects are created, when a full copy is probably required
 
Additional issues should be created and linked to this one

See https://github.com/pace-neutrons/Horace/issues/393 for a list of functions that perform operations on/use pixels and may need updating for file-backed `PixelData` objects.

**Comment by nickbattam-tessella** [comment]
Create linked tickets for each function or discrete code-block to aid tracking

**Comment by nickbattam-tessella** [comment]
Closed as superseded by #434: implementation shifted to algorithm focussed priorities

**Comment by cmarooney-stfc** [comment]
@nickbattam-tessella @hsautessella  Hi Nick, Harry. Noting that this is in the done column. Appreciating that this has been put on the back burner to get the algorithms in #434 done but the items above #398, #400, #401 seem to have been postponed rather than finished so wondering if Done is the best location for this. thanks Chris

**Comment by hsautessella** [comment]
The intention of this ticket was to enable Horace to work with user-facing file-backed objects. We've since agreed that using file-backed objects under-the-hood and hidden from users was simpler (see the [relevant ADR](https://github.com/pace-neutrons/Horace/blob/master/documentation/adr/0018-algorithm-migration-to-paged-files.md)). 

All children of this ticket should be closed (or "_Done_"), not postponed.
