### ISSUE TITLE
Support general coordinate transformations and generic projections

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#34]
Extend SQW projections to support general co-ordinate transformations.

The current implementation supports linear cuts. The requirement currently is to support spherical and cylindrical projections.

The implementation should be designed to support the definition of further projections in a similar way.

- [x] #462 Bugs in combine
- [x] #463 Documenting changes in a cut
- [x] #443 Combine_sqw looses pixels
- [x] #447 Clarify urange
- [x] #485 high-level design
- [x] #591  Extract projection, used in sqw generation from data_sqw_dnd
- [x] #510 Unclear axis ranges in combine_sqw
- [x] #464 symmetrise_sqw fails for non-orthogonal lattice and other complex cases
- [x] #653 Combine sqw fails for non-orthogonal lattice and other complex cases
- [x] #651 uoffset is expressed in different coordinate systems in different places of the code
- [x] #716
- [x] #803  -- Mainly done though the result still may be improved
- [x] #804
- [x] #810
- [x] #796
- [ ] #825
- [x] #797
- [x] #893 -- new file format
- [x] #943  -- spherical projection
- [ ] #892
- [ ]  #798
- [ ] #799
- [x] #801
- [ ] #805
- [ ] #800
- [ ] #511

**Comment by abuts** [comment]
Fully addressed by #892 except the parts taken by @oerc0122
