### ISSUE TITLE
EPIC: Benchmarking PACE

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Horace#676]
Create a number of reliable benchmarks for measuring timings and approximating scaling for use in the CI. 

These benchmarks will need to cover calculations from various parts of the code at various different scales. Ideally they would cover:
- Memory types:
   - All in memory
   - File-backed
   - Swap(?)
- Parallel types (where available):
   - Serial
   - MPI
   - Poor man's MPI
   - Parpool
and should not take a huge amount of time and resources to perform, otherwise the Jenkins will have to waste time downloading excessively large files and given it is a shared system, it would be unfair to other users to run this too regularly for large amounts of time. Possible exceptions might be if it were to be scheduled weekly during weekend hours to not interfere with others' jobs.

The scaling of the tasks should be known so that clear estimates can be made against the feasibility for the scale of files that PACE is intended to deal with (TB+) and give reliable estimates as to the code speeds.

Current benchmarking consists of scripts set up to perform `combine_sqw` and `cut_sqw` on 3 different file sizes and 6 different cuts, allowing basic averages to be calculated. 

Suggested Steps:

- [x] 1 - Create a list of areas of the code which need benchmarking
- [ ] 2 - Determine approximate scaling (with system size and processors, etc) for each of these areas
- [x] 3 - Develop scripts and data based on the measurements in (2) to create benchmarks
- [ ] 4 - Set up a regular benchmark pipeline in the Jenkins CI to measure against
