### ISSUE TITLE
C++ communicator for MPI framework

### ISSUE THREAD

**Issue by nickbattam-tessella** [pace-neutrons/Horace#68]
Herbert ticket: https://github.com/pace-neutrons/Herbert/issues/6
Contributing Horace tickets:
- [x] Documentation https://github.com/pace-neutrons/Horace/issues/154 
- [x] https://github.com/pace-neutrons/Horace/issues/126
- [x] [CPP Communicator does not pass persistent messages](https://github.com/pace-neutrons/Herbert/issues/155)
- [ ] Blocking send/recieve handler (https://github.com/pace-neutrons/Horace/issues/69)
- [x] Async send/recieve handler (https://github.com/pace-neutrons/Horace/issues/70)
- [x] Handle failure modes (https://github.com/pace-neutrons/Horace/issues/74)

**Comment by nickbattam-tessella** [comment]
Copy of ticket made in Horace repo to support tracking on the project board
