### ISSUE TITLE
Single-file backed operations 

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Horace#868]
- [ ] Make `PixelTmpFileManager` handle single files
- [ ] Split `PixelData` into `PixelDataFilebacked` and `PixelDataMemory`
- [ ] Add supporting functions (`advance`, `get_pix_in_ranges`, etc.)
- [ ] Remove "dirty page" functions
- [ ] See if creating parallel wrappers possible
- [ ] fix #844
