### ISSUE TITLE
EPIC: Add filebacking support with refactor to all SQW level operations

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Horace#973]
Look at other `sqw` operations and ensure that they appropriately support filebacking

- [x] IX_dataset_1d.m
- [x] IX_dataset_2d.m
- [x] IX_dataset_3d.m
- [x] binary_op_manager_single.m
- [x] calculate_qsqr_bins.m
- [x] calculate_qsqr_w_bins.m
- [x] calculate_qsqr_w_pixels.m
- [x] #1126
- [x] #1125
- [x] #1114
- [x] change_crystal.m
- [x] #1127
- [x] combine_sqw.m
- [x] copy.m
- [x] cut.m
- [x] cut_sym.m
- [x] dimensions_match.m
- [x] display.m
- [x] distribute.m
- [x] func_eval.m
- [x] generate_cube_sqw.m
- [x] get_efix.m
- [x] get_inst_class.m
- [x] get_mod_pulse.m
- [x] get_nearest_pixels.m
- [x] get_proj_and_pbin.m
- [x] has_pixels.m
- [x] head.m
- [x] header_average.m
- [x] is_cut_equal.m
- [x] join.m
- [x] lattice_parameters.m
- [x] mask.m
- [x] mask_pixels.m
- [x] mask_random_fraction_pixels.m
- [x] mask_random_pixels.m
- [x] multifit.m
- [x] noisify.m
- [x] #1118
- [x] #1124
- [x] recompute_bin_data.m
- [x] refine_crystal_strip_pars.m
- [x] replicate.m
- [x] resolution_plot.m
- [x] #1115
- [x] section.m
- [x] set_efix.m
- [x] set_instrument.m
- [x] set_mod_pulse.m
- [x] set_sample.m
- [x] shift_energy_bins.m
- [x] shift_pixels.m
- [x] #889 
- [x] sigvar.m
- [x] sigvar_get.m
- [x] sigvar_set.m
- [x] sigvar_size.m
- [x] slim.m
- [x] smooth.m
- [x] #1120
- [x] #1119
- [x] sqw.m
- [x] sqw_eval_pix.m
- [x] symmetrise_sqw.m
- [x] tobyfit.m
- [x] #1116
- [x] #1122
- [x] #1117
- [x] #1123
- [x] unary_op_manager.m
- [x] value.m
- [x] write_sqw.m

**Comment by oerc0122** [comment]
Removed `shift_pixels` from this epic as this stage is complete.
